bharathdasaraju@MacBook-Pro unittesting $ python3 -m unittest
F
======================================================================
FAIL: test_lookup_by_name (test_phonebook.PhoneBookTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bharathdasaraju/PycharmProjects/unittesting/test_phonebook.py", line 12, in test_lookup_by_name
    self.assertEqual("123456", number)
AssertionError: '123456' != None

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)

bharathdasaraju@MacBook-Pro unittesting $

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

bharathdasaraju@MacBook-Pro unittesting $ python3 -m unittest
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
bharathdasaraju@MacBook-Pro unittesting $


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Testing started at 17:55 ...
/usr/local/bin/python3.7 "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_unittest_runner.py" --path /Users/bharathdasaraju/PycharmProjects/python_unittests/test_phonebook.py
Launching unittests with arguments python -m unittest /Users/bharathdasaraju/PycharmProjects/python_unittests/test_phonebook.py in /Users/bharathdasaraju/PycharmProjects/python_unittests



Ran 2 tests in 0.002s

OK

Process finished with exit code 0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


bharathdasaraju@MacBook-Pro python_unittests $ python3 -m unittest
..
----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
bharathdasaraju@MacBook-Pro python_unittests $


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~